<?php
$update[0]='admin';
$update[1]='images';
$update[2]='language';
$update[3]='system';
$update[4]='templates';
$update[5]='update_db';
$update[6]='lateral_login.php';
$update[7]='login.php';
$update[8]='login_requiered.php';
$update[9]='lost_pass.php';
$update[10]='profile_activate.php';
$update[11]='new_register.php';
$update[12]='profile_edit.php';
$update[13]='profile_info.php';
$update[14]='register_ad.php';
$update[15]='register_advantages.php';
$update[16]='success_register.php';
?>