<?php
$update[0]='admin';
$update[1]='email';
$update[2]='images';
$update[3]='language';
$update[4]='layout';
$update[5]='system/eventos_funcs.php';
$update[6]='system/functions.php';
$update[7]='system/main_funcs.php';
$update[8]='system/main_lateral_funcs.php';
$update[9]='system/management_events.php';
$update[10]='system/profile_info.php';
$update[11]='update_db';
$update[12]='edit_event_cats.php';
$update[13]='main.php';
$update[14]='management_events.php';
?>